# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: php:7.4
build:
    flavor: composer

dependencies:
    php:
        composer/composer: '^2'

variables:
    env:
        # Tell Shopware to always install in production-mode.
        SHOPWARE_ENV: prod
        # Instance ID is empty by default, change to something unique in your project
        INSTANCE_ID: ''
        # Enable HTTP Cache to get cache-control headers
        SHOPWARE_HTTP_CACHE_ENABLED: 1
        # NVM and Node.js versions to install
        NVM_VERSION: v0.39.0
        NODE_VERSION: v12.22.7
        # Use different redis dbs for cache and sessions
        REDIS_CACHE_DATABASE: 0
        REDIS_SESSION_DATABASE: 2
    php:
        upload_max_filesize: 6M

# Specify additional PHP extensions that should be loaded.
runtime:
    extensions:
        - ctype
        - dom
        - iconv
        - mbstring
        - fileinfo
        - intl
        - redis
        - sodium

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        set -e

        # install nvm
        unset NPM_CONFIG_PREFIX
        export NVM_DIR="$PLATFORM_APP_DIR/.nvm"
        # install.sh will automatically install NodeJS based on the presence of $NODE_VERSION
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        # have nvm available and load the correct node version in your ssh session
        echo 'unset NPM_CONFIG_PREFIX' >> .bash_profile
        echo 'export NO_UPDATE_NOTIFIER=1' >> .bash_profile
        echo 'export NVM_DIR="$PLATFORM_APP_DIR/.nvm"' >> .bash_profile
        echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> .bash_profile

        # Disable UI installer
        touch install.lock

        # compile theme and save config for later (will be moved to mount).
        # warnings can be ignored (the process is trying to access Redis which is not yet available)
        export CI=true
        ./bin/build-js.sh
        mkdir build-tmp
        cp -R files/theme-config build-tmp

        # save plugin config for later (will be moved to mount)
        cp var/plugins.json build-plugins.json

    deploy: |
        set -e

        # load nvm to use the correct node version for any following commands
        unset NPM_CONFIG_PREFIX
        export NO_UPDATE_NOTIFIER=1
        export NVM_DIR="$PLATFORM_APP_DIR/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        # restore theme config from build to mount in case theme needs rebuilding during runtime
        cp -R build-tmp/theme-config files/

        # restore plugin config to mount
        cp build-plugins.json var/plugins.json

        # Initialize the Shopware site's data set if it's not already installed.
        # (This is only for demo/first install and can be removed once Shopware is initialized)
        if [ ! -f $PLATFORM_APP_DIR/installer/installed ]; then
            # setup the environment

            # create database with a basic setup (admin user and storefront sales channel).
            # this will try to run theme:compile which cannot be disabled, so it will throw a bunch of warnings
            # that can be ignored (we use stateless build anyway, so this is done already at this point)
            echo "Running system:install (Warnings for theme:compile can be ignored)"
            bin/console system:install --create-database --basic-setup --force

            # generate JWT
            echo "Running system:generate-jwt-secret"
            bin/console system:generate-jwt-secret

            # refresh plugins and enable PaaS Plugin
            bin/console plugin:refresh
            bin/console plugin:install --activate SwagPaas

            # mark system as installed
            touch $PLATFORM_APP_DIR/installer/installed
        fi;

        if [ "$PLATFORM_ENVIRONMENT_TYPE" != production ]; then
            export FRONTEND_URL=`echo $PLATFORM_ROUTES | base64 --decode | jq -r 'to_entries[] | select(.value.id=="shopware") | .key'`
            bin/console sales-channel:update-domain "$FRONTEND_URL"
        fi

        # optional: run migration automatically with deploy
        bin/console database:migrate --all
        bin/console cache:clear

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:mysql"
    rediscache: "cacheredis:redis"
    # uncomment if you want to use elasticsearch
    # essearch: "searchelastic:elasticsearch"
    # uncomment if you want to use rabbitmq
    # rabbitmqqueue: "queuerabbit:rabbitmq"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/files":
        source: local
        source_path: "files"
    "/public/media":
        source: local
        source_path: "public/media"
    "/public/thumbnail":
        source: local
        source_path: "public/thumbnail"
    "/config/secrets":
        source: local
        source_path: "config/secrets"
    "/config/jwt":
        source: local
        source_path: "config/jwt"
    "/var":
        source: local
        source_path: "var"
    "/installer":
        source: local
        source_path: "installer"
    "/.global":
        source: local
        source_path: "global"
    "/.cache":
        source: local
        source_path: ".cache"
    "/custom/apps":
        source: local
        source_path: "custom/apps"
    "/custom/plugins":
        source: local
        source_path: "custom/plugins"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "public"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            expires: 24h
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                    expires: 4w

workers:
    queue:
        disk: 128
        commands:
            start: |
                bin/console messenger:consume default --memory-limit=$(cat /run/config.json | jq .info.limits.memory)M --time-limit=295
